CREATE TABLE `quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`effectiveDate` datetime NOT NULL,
	`policyState` varchar(50) NOT NULL,
	`currentlyInsured` int NOT NULL,
	`targetPremium` int,
	`dotNumber` varchar(20),
	`mcNumber` varchar(20),
	`ein` varchar(20),
	`businessName` varchar(255) NOT NULL,
	`hasDba` int NOT NULL,
	`dbaName` varchar(255),
	`businessStructure` varchar(50) NOT NULL,
	`website` varchar(255),
	`yearEstablished` int NOT NULL,
	`mailingAddress` text NOT NULL,
	`mailingCity` varchar(100) NOT NULL,
	`mailingState` varchar(50) NOT NULL,
	`mailingZip` varchar(10) NOT NULL,
	`garagingAddress` text,
	`garagingCity` varchar(100),
	`garagingState` varchar(50),
	`garagingZip` varchar(10),
	`sameAsMailingAddress` int NOT NULL,
	`allVehiclesSameLocation` int NOT NULL,
	`selectedCoverages` json NOT NULL,
	`contactFirstName` varchar(100) NOT NULL,
	`contactLastName` varchar(100) NOT NULL,
	`contactEmail` varchar(320) NOT NULL,
	`contactPhone` varchar(20) NOT NULL,
	`trucks` json NOT NULL,
	`trailers` json NOT NULL,
	`drivers` json NOT NULL,
	`commodities` json NOT NULL,
	`status` enum('pending','under_review','approved','issued','rejected') NOT NULL DEFAULT 'pending',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotes_id` PRIMARY KEY(`id`)
);
