// States where Trux Insurance is licensed to operate
export const LICENSED_STATES = [
  'Arizona',
  'Colorado',
  'Florida',
  'Georgia',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kentucky',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Nevada',
  'North Carolina',
  'Ohio',
  'Pennsylvania',
  'South Carolina',
  'Tennessee',
  'Texas',
  'Virginia',
  'Wisconsin',
];
